# Generated by Django 5.0.6 on 2025-11-21 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Plot', max_length=255)),
                ('x_label', models.CharField(default='X Values', max_length=100)),
                ('y_label', models.CharField(default='Y Values', max_length=100)),
                ('plot_type', models.CharField(choices=[('line', 'Line Plot'), ('scatter', 'Scatter Plot'), ('bar', 'Bar Chart')], default='line', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='plots/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('x_data', models.TextField(help_text='Comma-separated X values')),
                ('y_data', models.TextField(help_text='Comma-separated Y values')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
